Vagrant.configure("2") do |config|
  # Especifica la caja que deseas usar
  config.vm.box = "ubuntu/bionic64"  # Puedes cambiar a otra caja si lo deseas

  # Configuraciones adicionales (puedes agregar más según sea necesario)
  config.vm.network "forwarded_port", guest: 80, host: 8080  # Redirigir puertos
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"  # Asigna memoria
  end
end

